version: "3.7"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        - MC19_VERSION=${MC19_VERSION}

  release:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
      args:
        - MC19_VERSION=${MC19_VERSION}
    # This is set this way to make things easier in the Actions workflows.
    image: image

  run-model:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
      args:
        - MC19_VERSION=${MC19_VERSION}
    environment:
      - MODEL_REPO_ROOT=/root/Github/covidmodel
      - WOLFRAM_USER
      - WOLFRAM_PASSWORD
    volumes:
      - ./test/test-job.json:/data/input/inputFile.json:ro
      - ./output:/data/output:rw

  remote-image:
    image: docker.pkg.github.com/${GITHUB_REPO:-covid-modeling/model-runner}/modelingcovid-covidmodel-connector:master
    tty: true
    environment:
      - MODEL_REPO_ROOT=/root/Github/covidmodel
      - WOLFRAM_USER
      - WOLFRAM_PASSWORD
    volumes:
      - ./test/test-job.json:/data/input/inputFile.json:ro
      - ./output:/data/output:rw
